2022-11-02 11:42:25,150 ERROR - Internal Server Error: /posts/create/ - /home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/utils/log.py - (<class 'news.models.Author.DoesNotExist'>, DoesNotExist('Author matching query does not exist.'), <traceback object at 0x7fe05af4a000>)
Traceback (most recent call last):
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/old/PycharmProjects/DjangoEDU/NewsPaper/news/views.py", line 70, in form_valid
    self.object.postAuthor = Author.objects.get(
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
news.models.Author.DoesNotExist: Author matching query does not exist.
2022-11-02 11:42:25,152 ERROR - "POST /posts/create/ HTTP/1.1" 500 112807 - /home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py - None
2022-11-02 11:42:28,892 ERROR - Internal Server Error: /posts/create/ - /home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/utils/log.py - (<class 'news.models.Author.DoesNotExist'>, DoesNotExist('Author matching query does not exist.'), <traceback object at 0x7fe068960a00>)
Traceback (most recent call last):
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/old/PycharmProjects/DjangoEDU/NewsPaper/news/views.py", line 70, in form_valid
    self.object.postAuthor = Author.objects.get(
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
news.models.Author.DoesNotExist: Author matching query does not exist.
2022-11-02 11:42:28,893 ERROR - "POST /posts/create/ HTTP/1.1" 500 112807 - /home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py - None
2022-11-02 11:42:40,505 ERROR - Internal Server Error: /posts/create/ - /home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/utils/log.py - (<class 'news.models.Author.DoesNotExist'>, DoesNotExist('Author matching query does not exist.'), <traceback object at 0x7fe059e5f900>)
Traceback (most recent call last):
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/home/old/PycharmProjects/DjangoEDU/NewsPaper/news/views.py", line 70, in form_valid
    self.object.postAuthor = Author.objects.get(
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
news.models.Author.DoesNotExist: Author matching query does not exist.
2022-11-02 11:42:40,505 ERROR - "POST /posts/create/ HTTP/1.1" 500 112807 - /home/old/PycharmProjects/DjangoEDU/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py - None
